#ifndef DETOURMODKIT_HPP
#define DETOURMODKIT_HPP

/**
 * @file DetourModKit.hpp
 * @brief Central header file for DetourModKit library.
 * @details This header provides a single include point for all DetourModKit functionality, along with convenient
 *          namespace aliases for common usage patterns. Include this header to access all DetourModKit features.
 */

// Version information (generated by CMake)
#include "DetourModKit/version.hpp"

// Core functionality headers
#include "DetourModKit/config.hpp"
#include "DetourModKit/hook_manager.hpp"
#include "DetourModKit/input_codes.hpp"
#include "DetourModKit/logger.hpp"
#include "DetourModKit/async_logger.hpp"
#include "DetourModKit/input.hpp"

// Module headers
#include "DetourModKit/bootstrap.hpp"
#include "DetourModKit/diagnostics.hpp"
#include "DetourModKit/diagnostics_dump.hpp"
#include "DetourModKit/drift_manifest.hpp"
#include "DetourModKit/event_dispatcher.hpp"
#include "DetourModKit/filesystem.hpp"
#include "DetourModKit/format.hpp"
#include "DetourModKit/math.hpp"
#include "DetourModKit/memory.hpp"
#include "DetourModKit/profiler.hpp"
#include "DetourModKit/rtti.hpp"
#include "DetourModKit/rtti_dissect.hpp"
#include "DetourModKit/scan.hpp"
#include "DetourModKit/worker.hpp"

/**
 * @brief Convenient namespace aliases for common DetourModKit usage patterns.
 * @details These aliases allow for shorter, more readable code when using DetourModKit functionality extensively.
 *          Example: DMK::Logger instead of DetourModKit::Logger.
 */
namespace DMK = DetourModKit;
namespace DMKConfig = DetourModKit::Config;
namespace DMKScan = DetourModKit::scan;
namespace DMKString = DetourModKit::String;
namespace DMKFormat = DetourModKit::Format;
namespace DMKFilesystem = DetourModKit::Filesystem;
namespace DMKMemory = DetourModKit::memory;
namespace DMKMath = DetourModKit::Math;
namespace DMKBootstrap = DetourModKit::Bootstrap;
namespace DMKRtti = DetourModKit::Rtti;

#ifndef DMK_NO_SHORT_NAMES
/**
 * @brief Convenient type aliases for commonly used DetourModKit types.
 * @details These aliases provide shorter names for frequently used types. Define DMK_NO_SHORT_NAMES before including
 *          this header to disable them.
 */
using DMKLogger = DetourModKit::Logger;
using DMKStoppableWorker = DetourModKit::StoppableWorker;
using DMKInputBindingGuard = DetourModKit::Config::InputBindingGuard;
using DMKHookManager = DetourModKit::HookManager;
using DMKLogLevel = DetourModKit::LogLevel;
using DMKHookStatus = DetourModKit::HookStatus;
using DMKHookType = DetourModKit::HookType;
using DMKHookConfig = DetourModKit::HookConfig;
using DMKAsyncLogger = DetourModKit::AsyncLogger;
using DMKAsyncLoggerConfig = DetourModKit::AsyncLoggerConfig;
using DMKOverflowPolicy = DetourModKit::OverflowPolicy;
using DMKInputManager = DetourModKit::InputManager;
using DMKInputPoller = DetourModKit::InputPoller;
using DMKInputMode = DetourModKit::InputMode;
using DMKInputSource = DetourModKit::InputSource;
using DMKInputCode = DetourModKit::InputCode;
using DMKKeyCombo = DetourModKit::Config::KeyCombo;
using DMKKeyComboList = DetourModKit::Config::KeyComboList;
using DMKInputBinding = DetourModKit::InputBinding;
using DMKProfiler = DetourModKit::Profiler;
using DMKScopedProfile = DetourModKit::ScopedProfile;
using DMKProfileSample = DetourModKit::ProfileSample;
#endif // DMK_NO_SHORT_NAMES

/**
 * @brief Explicitly shuts down all DetourModKit singletons in the correct order.
 * @details This function should be called before process exit or DLL unload to ensure proper cleanup without
 *          use-after-free errors. It shuts down singletons in reverse dependency order: the Config auto-reload watcher
 *          first, then InputManager, HookManager, Memory cache, the Config registry, then Logger last. After calling
 *          this function, the singletons are in a safe state for destruction.
 *
 * @note This function is idempotent - calling it multiple times is safe.
 * @note noexcept: every teardown step it invokes is itself noexcept, so the wrapper carries the no-throw guarantee.
 * @note Each subsystem detects if it is running under the Windows loader lock (e.g. from DllMain/DLL_PROCESS_DETACH or
 *       FreeLibrary) and will detach background threads instead of joining them to avoid deadlock. However, calling
 *       DMK_Shutdown() before DLL_PROCESS_DETACH is still the recommended practice for a clean orderly shutdown.
 * @note The async-logger StringPool singleton is intentionally leaked and is
 *       NOT reclaimed by this function; the OS releases the memory at process exit. See
 *       DetourModKit::detail::StringPool for the rationale.
 */
inline void DMK_Shutdown() noexcept
{
    // Shutdown in reverse dependency order:
    // 1. Config auto-reload watcher first: its background thread can fire the user on_reload callback at any moment, so
    //    it must stop before any consumer state that callback may touch is torn down. Idempotent and noexcept.
    DetourModKit::Config::disable_auto_reload();

    // 2. InputManager (polling thread may invoke callbacks that log)
    DetourModKit::InputManager::get_instance().shutdown();

    // 3. HookManager (may have been logging via Logger)
    DetourModKit::HookManager::get_instance().shutdown();

    // 4. Memory cache (background cleanup thread must stop before Logger shuts down)
    DetourModKit::memory::shutdown_cache();

    // 5. Clear registered config items (static vector cleanup)
    DetourModKit::Config::clear_registered_items();

    // 6. Logger last (no more logging after this)
    DetourModKit::Logger::get_instance().shutdown();
}

#endif // DETOURMODKIT_HPP
