#ifndef DETOURMODKIT_HPP
#define DETOURMODKIT_HPP

/**
 * @file DetourModKit.hpp
 * @brief The DetourModKit umbrella header and the process-lifecycle surface (Session / bootstrap / ModInfo).
 * @details A single include point for the whole kit. It aggregates every public module header and then adds the RAII
 *          Session and the DllMain bootstrap entry points that own a mod's process lifetime. Include this to reach all
 *          of DetourModKit, or include the individual module headers directly for a leaner compile.
 *
 * @note This header does not include <windows.h>. The Win32 module handle is exposed through the opaque
 *       DetourModKit::ModuleHandle alias, so a consumer translation unit that needs <windows.h> for its own DllMain
 *       must include it directly; a real HMODULE binds to ModuleHandle with no cast.
 */

// Version information (generated by CMake).
#include "DetourModKit/version.hpp"

// Foundation vocabulary and every public module. bootstrap.hpp is deliberately absent: its Session/bootstrap surface
// lives in this header now.
#include "DetourModKit/anchor.hpp"
#include "DetourModKit/async_logger.hpp"
#include "DetourModKit/async_logger_config.hpp"
#include "DetourModKit/config.hpp"
#include "DetourModKit/diagnostics.hpp"
#include "DetourModKit/detail/drift_manifest.hpp"
#include "DetourModKit/detail/event_dispatcher.hpp"
#include "DetourModKit/filesystem.hpp"
#include "DetourModKit/format.hpp"
#include "DetourModKit/hook.hpp"
#include "DetourModKit/input.hpp"
#include "DetourModKit/input_codes.hpp"
#include "DetourModKit/logger.hpp"
#include "DetourModKit/math.hpp"
#include "DetourModKit/memory.hpp"
#include "DetourModKit/profiler.hpp"
#include "DetourModKit/rtti.hpp"
#include "DetourModKit/rtti_dissect.hpp"
#include "DetourModKit/scan.hpp"
#include "DetourModKit/detail/worker.hpp"

#include <functional>
#include <span>
#include <string_view>

// HMODULE is `struct HINSTANCE__ *`. Forward-declaring the incomplete tag lets this public header expose the
// module-handle type without pulling <windows.h> (and its macro soup) into every consumer translation unit. A TU that
// also includes <windows.h> sees the identical type, so a real HMODULE binds with no cast. The implementation file
// (src/dmk.cpp) includes <windows.h> directly for the Win32 calls in the function bodies.
struct HINSTANCE__;

namespace DetourModKit
{
    /**
     * @brief Opaque Win32 module handle, identical to HMODULE (which is `struct HINSTANCE__ *`).
     * @details Aliased so the public surface needs no <windows.h>; a real HMODULE binds to it with no cast.
     */
    using ModuleHandle = ::HINSTANCE__ *;

    /**
     * @struct ModInfo
     * @brief Identity, single-instance gating, process gating, and async-logger settings for a mod.
     * @details Passed to Session::start() / bootstrap(). Every field is a borrowed view or a value copied out before
     *          the call returns, so a ModInfo built from string literals at the call site is sufficient; nothing here
     *          is retained past setup. @p name doubles as the logger prefix and the mod's human identity.
     *
     *          @p game_process_name, when non-empty, is compared (case-insensitive) against the running executable's
     *          basename; a mismatch makes start() return ErrorCode::ProcessMismatch so the DLL can decline to load in
     *          the wrong process. @p instance_mutex_prefix, when non-empty, creates a per-PID named mutex so a second
     *          load of the same mod bails out with ErrorCode::InstanceAlreadyRunning.
     *
     *          There is no ini path here: the config registry is bind-then-load (binds register first, then load()
     *          applies file values), so a mod loads its INI from on_ready via session.ini().load(path) AFTER its binds
     *          exist, not implicitly at start() when the registry is still empty.
     */
    struct ModInfo
    {
        std::string_view name{};
        std::string_view log_file{};
        std::string_view game_process_name{};
        std::string_view instance_mutex_prefix{};
        AsyncLoggerConfig log{};
    };

    /**
     * @class Session
     * @brief RAII owner of a mod's process lifetime: single-instance guard, logger configuration, its input binding
     *        scope, and the correctly ordered teardown of every process-wide subsystem.
     * @details A Session makes process-lifetime teardown automatic and correctly ordered, replacing an error-prone
     *          manual shutdown that had to sequence each subsystem by hand. It is constructed two ways:
     *
     *          - Session::start(ModInfo): the synchronous, directly-held path (the one tests and simple hosts use). It
     *            runs the process gate, acquires the single-instance mutex, and configures the logger, then returns a
     *            live Session by value. When that value is destroyed, ~Session runs the ordered teardown.
     *          - bootstrap(ModInfo, on_ready): the DllMain path. It performs the same setup under the loader lock, then
     *            hands the Session to a worker thread that runs on_ready off the loader lock and destroys the Session
     *            (the ordered teardown) once bootstrap_detach() signals it. See bootstrap().
     *
     *          Teardown ordering lives in exactly one place, the explicit ~Session body: first scope().clear() releases
     *          this session's input bindings (reverse insertion order, so a Hold binding's release edge fires before
     *          the bindings it depends on), then the process-wide subsystems tear down in reverse dependency order --
     *          the config auto-reload watcher, the input poll thread, the memory cache, the config registry, and the
     *          logger LAST (every prior step may still log). Each subsystem shutdown embeds its own loader-lock guard
     *          (join when safe, detach-and-leak when the loader lock is held), so ~Session delegates the join/leak
     *          decision to the leaves rather than making one central, and therefore wrong, choice.
     *
     *          Hooks are NOT owned by the Session: each hook lives in a caller-held Hook handle and unhooks when that
     *          handle drops, so hook lifetime is orthogonal to the session and correctly ordered by the caller's own
     *          scopes.
     *
     * @note A Session is move-only. A moved-from (or abandon()ed) Session is inert: its destructor does nothing, so a
     *       double-drop never double-tears-down. A mod DLL has one process lifetime, so only one Session is active at a
     *       time; a second start()/bootstrap() returns ErrorCode::SessionAlreadyActive.
     * @note Session::start, on_ready, ~Session, and abandon() run single-threaded on the init/teardown thread. Do not
     *       call them from a hook, an input callback, or a config-reload callback.
     */
    class Session
    {
    public:
        /**
         * @brief Synchronously builds a Session: process gate, single-instance mutex, and logger configuration.
         * @param info Mod identity, gating, and async-logger settings.
         * @return A live Session on success, or an ErrorCode-bearing failure: ProcessMismatch (wrong executable),
         *         InstanceAlreadyRunning (a duplicate load holds the mutex), SessionAlreadyActive (a session already
         *         exists in this process), SystemCallFailed (a Win32 primitive failed; Error::detail = GetLastError()),
         *         or OutOfMemory (an allocation during logger configuration threw).
         * @note noexcept by contract: bootstrap() calls this under the loader lock, where an escaping exception is
         *       undefined behavior, so every throwing step is caught and mapped to a Result failure.
         */
        [[nodiscard]] static Result<Session> start(const ModInfo &info) noexcept;

        /** @brief Move-constructs, transferring the live teardown; the moved-from Session is left inert. */
        Session(Session &&other) noexcept;
        /** @brief Move-assigns: ends this Session (ordered teardown) if it was active, then adopts @p other. */
        Session &operator=(Session &&other) noexcept;
        /** @brief Deleted: Session is move-only; its teardown and single-instance guard cannot be copied. */
        Session(const Session &) = delete;
        Session &operator=(const Session &) = delete;

        /**
         * @brief Runs the ordered teardown if this Session is active; otherwise a no-op (moved-from / abandoned).
         */
        ~Session() noexcept;

        /**
         * @brief The process-default logger this session configured. Convenience for `DetourModKit::log()`.
         */
        [[nodiscard]] Logger &log() const noexcept;

        /**
         * @brief A handle to the process configuration registry. Load the mod's INI here (after registering binds):
         *        `session.ini().load(path)`.
         */
        [[nodiscard]] config::Ini ini() const noexcept;

        /**
         * @brief The process input manager. Convenience for `input::Input::instance()`.
         */
        [[nodiscard]] input::Input &input() const noexcept;

        /**
         * @brief This session's input binding scope. Add BindingGuards here; ~Session clears it first (reverse order).
         */
        [[nodiscard]] input::Scope &scope() noexcept;

        /**
         * @brief True while this Session owns a live teardown; false once moved-from or abandon()ed.
         */
        [[nodiscard]] explicit operator bool() const noexcept { return m_active; }

        /**
         * @brief Neutralizes the Session so its destructor does NOTHING: no scope clear, no subsystem teardown, no
         *        unhook, no logger flush, no thread join.
         * @details For DLL_PROCESS_DETACH with `lpReserved != NULL` (process termination) ONLY. On that path the OS has
         *          already terminated every other thread and is reclaiming the address space, so touching patched
         *          pages, flushing the logger, or joining a dead thread is at best pointless and at worst a UAF.
         *          abandon() drops all of it and lets the OS reclaim everything at exit. Never call it for an explicit
         *          FreeLibrary (lpReserved == NULL), where a real ordered teardown must run.
         */
        void abandon() noexcept;

    private:
        // The sole constructor, reached only through start(). Both the synchronous and the bootstrap paths build the
        // Session here, so the single-instance mutex is always Session-owned and released in exactly one place
        // (~Session); @p instance_mutex is null when ModInfo requested no single-instance guard.
        explicit Session(void *instance_mutex) noexcept;

        // The ordered teardown, factored out so ~Session and move-assignment (which must end the session it overwrites)
        // share exactly one implementation. A no-op on an inert Session; idempotent.
        void release() noexcept;

        // The mod's input bindings; cleared first in ~Session. Move-only, default-constructible: keeps Session movable.
        input::Scope m_scope;
        // The single-instance mutex handle (or null); CloseHandle'd in ~Session. Typed as void* so this public header
        // stays free of <windows.h>.
        void *m_instance_mutex{nullptr};
        // Gates the destructor. Transferred on move (source becomes inert), cleared by abandon().
        bool m_active{false};
    };

    /**
     * @brief DllMain DLL_PROCESS_ATTACH entry point: runs setup under the loader lock, then a worker thread that hosts
     *        the Session.
     * @details Auto-captures the calling module (DetourModKit links statically into the mod DLL, so its code address
     *          resolves to the mod's HMODULE), calls DisableThreadLibraryCalls, then runs the same setup as
     *          Session::start (process gate, single-instance mutex, logger configuration). On success it spawns a
     *          worker thread that:
     *            1. runs @p on_ready(session) OFF the loader lock (so it may allocate, load INIs, install hooks, and
     *               register bindings into session.scope() freely),
     *            2. blocks on the shutdown event until bootstrap_detach() (FreeLibrary) or request_shutdown() wakes it,
     *            3. destroys the Session -- the ordered teardown -- off the loader lock, so every subsystem leaf JOINS
     *               its thread cleanly.
     *
     *          @p on_ready returns Result<void> so an init failure is a value logged on the worker, never an exception
     *          crossing the loader lock. It is std::move_only_function so it may capture move-only setup state.
     *
     * @param info Mod identity, gating, and async-logger settings.
     * @param on_ready Called exactly once on the worker thread with the live Session.
     * @return An empty Result on success (the worker started), or a failure mirroring Session::start's error set
     *         (ProcessMismatch, InstanceAlreadyRunning, SessionAlreadyActive, SystemCallFailed, OutOfMemory).
     * @note Setup/control-plane only. Call it solely from DllMain's attach path -- it allocates, configures the logger,
     *       and starts a thread. noexcept by contract: it runs under the loader lock, so any internal throw is caught,
     *       the partial attach is rolled back, and a Result failure is returned rather than unwinding across the lock.
     */
    [[nodiscard]] Result<void> bootstrap(const ModInfo &info,
                                         std::move_only_function<Result<void>(Session &)> on_ready) noexcept;

    /**
     * @brief DllMain DLL_PROCESS_DETACH entry point. Routes by @p reserved (DllMain's lpvReserved).
     * @details Two paths, both loader-lock-safe:
     *
     *          - @p reserved == NULL (explicit FreeLibrary): signals the worker to run the ordered ~Session teardown
     *            OFF the loader lock, records an intentional-leak marker, and returns WITHOUT waiting or joining --
     *            blocking under the loader lock would deadlock any peer DllMain. A mod that needs a guaranteed-drained
     *            unload must call request_shutdown() before FreeLibrary and give the worker time to finish.
     *          - @p reserved != NULL (process termination): the OS has already killed the worker, so this takes the
     *            abandon path -- no teardown, no unhook, no flush, no join. Handles are closed without waiting and the
     *            OS reclaims the rest.
     *
     *          Idempotent: subsequent calls are no-ops.
     * @param reserved DllMain's lpvReserved (NULL for FreeLibrary, non-NULL for process exit).
     * @note Setup/control-plane only: call it solely from DllMain's DLL_PROCESS_DETACH path. Loader-lock-safe (it never
     *       waits or joins under the loader lock); best-effort on a bare FreeLibrary, where the worker drains
     *       asynchronously.
     */
    void bootstrap_detach(void *reserved) noexcept;

    /**
     * @brief Signals the bootstrap worker to run its teardown so a mod can drain cleanly before FreeLibrary.
     * @details Non-blocking: it does not wait for the worker. A no-op if bootstrap() never ran or teardown already
     *          completed. This is the handshake that turns a dynamic unload into a clean one: signal, let the worker
     *          join the subsystem threads while the DLL is still mapped, then FreeLibrary.
     * @note Callback-safe: safe from any thread (a hook, an input callback, or DllMain). It only signals an event and
     *       never allocates, waits, or joins.
     */
    void request_shutdown() noexcept;

    /**
     * @brief The module handle captured at bootstrap() time, or nullptr before bootstrap() / after detach or when only
     *        the synchronous Session::start path was used.
     */
    [[nodiscard]] ModuleHandle module_handle() noexcept;

    /**
     * @brief Hot-reload helper: drops the named input bindings and clears the config registry, keeping the process and
     *        its subsystems alive.
     * @details For a host that unloads one Logic DLL while the process continues. It removes each named binding from
     * the
     *          process-wide input manager (release callbacks suppressed, since they live in the unloading DLL and must
     *          not run under a loader lock), stops the config auto-reload watcher, then clears the config registry --
     *          the registered setters' call operators live in the unloading DLL's .text and would become
     *          use-after-unload hazards on the next load. Hooks are NOT touched: each is owned by a caller-held Hook
     *          handle and unhooks when that handle drops. Idempotent.
     *
     * @param binding_names Names registered via input::register_combo (or config::press_combo / hold_combo).
     * @note Setup/control-plane only and loader-lock-safe: intended for a Logic-DLL Shutdown() or a DllMain detach
     * path.
     *       noexcept and best-effort -- every internal throw (including logging) is caught, so nothing crosses the
     *       boundary.
     * @warning Stop and join every consumer-owned worker thread, and drop the Logic DLL's Hook handles, before the
     *          loader reclaims that DLL's .text -- a thread that fires a hook after the unload executes freed code.
     */
    void on_logic_dll_unload(std::span<const std::string_view> binding_names) noexcept;

    /**
     * @brief Hot-reload helper: clears EVERY input binding and the config registry, keeping the process alive.
     * @details The catch-all sibling of on_logic_dll_unload(). It clears all bindings through the process-wide input
     *          manager (keeping the manager re-usable for the next load, poll thread still running), stops the config
     *          auto-reload watcher, then clears the config registry, for the same use-after-unload reasons. Hooks are
     *          not touched (caller-owned). Idempotent.
     *
     * @note Setup/control-plane only and loader-lock-safe: safe from a Logic-DLL Shutdown() or a DllMain detach path.
     *       noexcept and best-effort -- internal throws (including logging) are caught, so nothing crosses the edge.
     * @warning In a host running multiple Logic DLLs over one process-wide DetourModKit, this rips out the OTHER Logic
     *          DLLs' bindings too; prefer on_logic_dll_unload() with an explicit name list in that topology. The same
     *          worker-thread and Hook-handle teardown warning as on_logic_dll_unload() applies.
     */
    void on_logic_dll_unload_all() noexcept;
} // namespace DetourModKit

#endif // DETOURMODKIT_HPP
