#ifndef DETOURMODKIT_HPP
#define DETOURMODKIT_HPP

/**
 * @file DetourModKit.hpp
 * @brief The DetourModKit umbrella header: a single include point for every public module.
 * @details Aggregates the foundation vocabulary, every public module header, and the process-lifecycle surface
 *          (Session / bootstrap / ModInfo, declared in DetourModKit/session.hpp). Include this to reach all of
 *          DetourModKit, or include the individual module headers directly for a leaner compile.
 */

// Version information (generated by CMake).
#include "DetourModKit/version.hpp"

// Foundation vocabulary and every public module, including the Session / bootstrap / ModInfo process-lifecycle surface
// (DetourModKit/session.hpp).
#include "DetourModKit/anchor.hpp"
#include "DetourModKit/async_logger_config.hpp"
#include "DetourModKit/config.hpp"
#include "DetourModKit/diagnostics.hpp"
#include "DetourModKit/detail/drift_manifest.hpp"
#include "DetourModKit/detail/event_dispatcher.hpp"
#include "DetourModKit/filesystem.hpp"
#include "DetourModKit/format.hpp"
#include "DetourModKit/hook.hpp"
#include "DetourModKit/input.hpp"
#include "DetourModKit/input_codes.hpp"
#include "DetourModKit/logger.hpp"
#include "DetourModKit/manifest.hpp"
#include "DetourModKit/math.hpp"
#include "DetourModKit/memory.hpp"
#include "DetourModKit/profiler.hpp"
#include "DetourModKit/rtti.hpp"
#include "DetourModKit/rtti_dissect.hpp"
#include "DetourModKit/scan.hpp"
#include "DetourModKit/session.hpp"
#include "DetourModKit/sighealth.hpp"
#include "DetourModKit/detail/worker.hpp"

#endif // DETOURMODKIT_HPP
